# Generated by Django 5.2.4 on 2025-07-14 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('counseling', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='counselor',
            new_name='counseling_service',
        ),
        migrations.CreateModel(
            name='CounselingService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('counselors', models.ManyToManyField(related_name='services', to='counseling.counselor')),
            ],
        ),
    ]
