# Generated by Django 5.2.4 on 2025-07-16 10:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('counseling', '0002_rename_counselor_appointment_counseling_service_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='counselor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='counseling.counselor'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='appointment',
            name='counseling_service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='counseling.counselingservice'),
        ),
    ]
