# Generated by Django 5.2.4 on 2025-09-01 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('counseling', '0003_appointment_counselor_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('youtube_url', models.URLField()),
                ('date_added', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
